import { MigrationProject, AuditLog } from "./types";

export const SAMPLE_PROJECTS: MigrationProject[] = [
  {
    id: "proj-superstore",
    name: "Global Superstore Retail",
    status: "Validated",
    progress: 85,
    tableauFileName: "Global_Superstore_v2026.twb",
    createdDate: "2026-07-01",
    metadata: {
      name: "Global Superstore Retail",
      version: "18.2",
      author: "Sarah Jenkins (Lead BI Engineer)",
      createdDate: "2026-06-25",
      publishedDate: "2026-06-28",
      datasources: [
        {
          id: "federated.Orders",
          name: "Orders+People (Superstore)",
          connection: {
            type: "postgresql",
            server: "postgres-prod-eu.data.enterprise.corp",
            database: "RetailWarehouse",
            schema: "sales_marts",
          },
          tables: [
            { table: "fact_orders", name: "Fact_Orders" },
            { table: "dim_customers", name: "Dim_Customers" },
            { table: "dim_products", name: "Dim_Products" },
            { table: "dim_location", name: "Dim_Location" },
          ],
          columns: [
            { name: "Order ID", id: "[Order ID]", datatype: "string", role: "dimension" },
            { name: "Order Date", id: "[Order Date]", datatype: "date", role: "dimension" },
            { name: "Customer ID", id: "[Customer ID]", datatype: "string", role: "dimension" },
            { name: "Product ID", id: "[Product ID]", datatype: "string", role: "dimension" },
            { name: "Sales", id: "[Sales]", datatype: "real", role: "measure" },
            { name: "Quantity", id: "[Quantity]", datatype: "integer", role: "measure" },
            { name: "Profit", id: "[Profit]", datatype: "real", role: "measure" },
            { name: "Discount", id: "[Discount]", datatype: "real", role: "measure" },
            { name: "Region", id: "[Region]", datatype: "string", role: "dimension" },
            { name: "Country", id: "[Country]", datatype: "string", role: "dimension" },
            { name: "Category", id: "[Category]", datatype: "string", role: "dimension" },
            { name: "Sub-Category", id: "[Sub-Category]", datatype: "string", role: "dimension" },
          ],
          calculatedFields: [
            {
              name: "Profit Margin %",
              id: "[Profit Margin %]",
              formula: "SUM([Profit]) / SUM([Sales])",
              datatype: "real",
              role: "measure",
              convertedDax: "Profit Margin % = \nDIVIDE(\n    SUM(Fact_Orders[Profit]),\n    SUM(Fact_Orders[Sales]),\n    0\n)",
              convertedM: "// Calculated at semantic model level as DAX Measure for dynamic aggregation.",
              explanation: "Translated standard ratio aggregation using Power BI DIVIDE function to safely handle division-by-zero scenarios.",
              complexity: "Low",
              daxType: "Measure",
              warnings: ["None. Clean conversion."],
              status: "Verified",
            },
            {
              name: "Category Sales (LOD FIXED)",
              id: "[Category Sales (LOD FIXED)]",
              formula: "{ FIXED [Category] : SUM([Sales]) }",
              datatype: "real",
              role: "measure",
              convertedDax: "Category Sales (LOD FIXED) = \nCALCULATE(\n    SUM(Fact_Orders[Sales]),\n    ALLEXCEPT(Fact_Orders, Dim_Products[Category])\n)",
              convertedM: "// Recommend maintaining this calculation in DAX via ALLEXCEPT for cross-filtering control.",
              explanation: "Tableau FIXED Level of Detail expression translated using CALCULATE with ALLEXCEPT. This locks the context filter to the Category column.",
              complexity: "High",
              daxType: "Measure",
              warnings: ["ALLEXCEPT removes other filters. Ensure this behaves correctly with page slicers."],
              status: "Verified",
            },
            {
              name: "Customer Lifetime Value Group",
              id: "[CLV Group]",
              formula: "IF [Sales] > 5000 THEN 'Platinum' ELSEIF [Sales] > 2000 THEN 'Gold' ELSE 'Silver' END",
              datatype: "string",
              role: "dimension",
              convertedDax: "CLV Group = \nSWITCH(\n    TRUE(),\n    Fact_Orders[Sales] > 5000, \"Platinum\",\n    Fact_Orders[Sales] > 2000, \"Gold\",\n    \"Silver\"\n)",
              convertedM: "Table.AddColumn(PreviousStep, \"CLV Group\", each if [Sales] > 5000 then \"Platinum\" else if [Sales] > 2000 then \"Gold\" else \"Silver\")",
              explanation: "Tableau multi-condition IF-ELSE statement translated to an optimized DAX SWITCH(TRUE(), ...) statement. Can also be handled during ETL in Power Query (M) as demonstrated.",
              complexity: "Medium",
              daxType: "Calculated Column",
              warnings: ["For premium semantic models, creating this as a Power Query M physical column is recommended for compression."],
              status: "Verified",
            },
            {
              name: "YoY Sales Growth %",
              id: "[YoY Sales Growth %]",
              formula: "(SUM([Sales]) - LOOKUP(SUM([Sales]), -1)) / LOOKUP(SUM([Sales]), -1)",
              datatype: "real",
              role: "measure",
              convertedDax: "YoY Sales Growth % = \nVAR CurrentSales = SUM(Fact_Orders[Sales])\nVAR PreviousYearSales = CALCULATE(SUM(Fact_Orders[Sales]), SAMEPERIODLASTYEAR(Dim_Calendar[Date]))\nRETURN\nDIVIDE(\n    CurrentSales - PreviousYearSales,\n    PreviousYearSales,\n    0\n)",
              convertedM: "// Time intelligence functions must be built in DAX on top of a standard Date table.",
              explanation: "Tableau LOOKUP table calculation converted to a robust DAX time intelligence model using SamePeriodLastYear, which leverages Power BI's built-in calendar table structures.",
              complexity: "High",
              daxType: "Measure",
              warnings: ["Requires a continuous date table in Power BI marked as 'Date Table'. SamePeriodLastYear will return blank if calendar gap exists."],
              status: "Verified",
            },
            {
              name: "Running Sales Sum",
              id: "[Running Sales Sum]",
              formula: "RUNNING_SUM(SUM([Sales]))",
              datatype: "real",
              role: "measure",
              convertedDax: "Running Sales Sum = \nCALCULATE(\n    SUM(Fact_Orders[Sales]),\n    FILTER(\n        ALLSELECTED(Dim_Calendar),\n        Dim_Calendar[Date] <= MAX(Dim_Calendar[Date])\n    )\n)",
              convertedM: "// Best practice: calculate cumulative totals dynamically in DAX reporting model.",
              explanation: "Tableau RUNNING_SUM table calculation converted to DAX dynamic cumulative measure using FILTER on ALLSELECTED calendar context.",
              complexity: "Medium",
              daxType: "Measure",
              warnings: ["Monitor query performance when used in high-cardinality matrix visuals."],
              status: "Verified",
            },
          ],
        },
      ],
      worksheets: [
        { name: "Sales Trend Analysis", visualType: "Line Chart", filters: [{ column: "Order Date" }] },
        { name: "Regional Revenue Matrix", visualType: "Cross Tab / Text Table", filters: [{ column: "Region" }] },
        { name: "Segment Profitability Map", visualType: "Map", filters: [{ column: "Category" }] },
        { name: "KPI Top Cards", visualType: "KPI Grid", filters: [] },
      ],
      dashboards: [
        { name: "Executive Business Overview", sheets: ["Sales Trend Analysis", "Regional Revenue Matrix", "KPI Top Cards"], layout: "Bento Container Layout" },
        { name: "Geographic Sales Intelligence", sheets: ["Segment Profitability Map"], layout: "Grid Split Layout" },
      ],
      parameters: [
        { id: "[Target Profit Margin]", name: "Target Profit Margin", datatype: "real" },
        { id: "[Forecast Year Range]", name: "Forecast Year Range", datatype: "integer" },
      ],
      unsupportedFeatures: [
        "Tableau Native Ad-hoc Grouping (requires Power BI calculated columns/groups)",
        "Level of Detail (LOD) Expressions: FIXED/INCLUDE/EXCLUDE (converted via CALCULATE/ALLEXCEPT)",
      ],
    },
    dataModel: {
      schemaType: "Star Schema",
      factTables: ["Fact_Orders"],
      dimensionTables: ["Dim_Customers", "Dim_Products", "Dim_Location", "Dim_Calendar"],
      bridgeTables: [],
      relationships: [
        { fromTable: "Fact_Orders", fromColumn: "CustomerID", toTable: "Dim_Customers", toColumn: "CustomerID", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
        { fromTable: "Fact_Orders", fromColumn: "ProductID", toTable: "Dim_Products", toColumn: "ProductID", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
        { fromTable: "Fact_Orders", fromColumn: "PostalCode", toTable: "Dim_Location", toColumn: "PostalCode", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
        { fromTable: "Fact_Orders", fromColumn: "OrderDateKey", toTable: "Dim_Calendar", toColumn: "DateKey", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
      ],
    },
    calculatedFields: [], // Overwritten dynamically by program
    validation: {
      rowCountMatch: true,
      columnCountMatch: true,
      totalsMatch: true,
      kpiMatch: true,
      discrepancyCount: 0,
      results: [
        { metricName: "Total Raw Orders Count", tableauValue: 51290, powerBiValue: 51290, variance: 0, status: "Pass" },
        { metricName: "Aggregated Gross Revenue", tableauValue: 12642500, powerBiValue: 12642500, variance: 0, status: "Pass" },
        { metricName: "Net Profit Margin (Overall)", tableauValue: 0.1158, powerBiValue: 0.1158, variance: 0, status: "Pass" },
        { metricName: "Category Sales (LOD Check)", tableauValue: 4851200, powerBiValue: 4851200, variance: 0, status: "Pass" },
        { metricName: "Distinct Customers Count", tableauValue: 4850, powerBiValue: 4850, variance: 0, status: "Pass" },
      ],
    },
    logs: [
      { timestamp: "10:14:02", level: "info", message: "Migration project 'Global Superstore Retail' initialized." },
      { timestamp: "10:14:05", level: "success", message: "Tableau XML .twb successfully uploaded and parsed by server." },
      { timestamp: "10:14:09", level: "info", message: "Extracted connection properties: PostgreSQL: 'postgres-prod-eu.data.enterprise.corp'" },
      { timestamp: "10:14:14", level: "info", message: "Schema analyzer detected Star Schema. Fact Table: Fact_Orders." },
      { timestamp: "10:14:22", level: "warn", message: "LOD calculation '[Category Sales (LOD FIXED)]' requires DAX context-override (ALLEXCEPT)." },
      { timestamp: "10:14:35", level: "success", message: "AI Formula Converter converted 5 out of 5 Tableau calculated fields to clean DAX." },
      { timestamp: "10:14:48", level: "success", message: "Validation Engine matched row counts and totals with 100.0% precision." },
    ],
  },
  {
    id: "proj-finance",
    name: "Enterprise Financial Performance",
    status: "Validated",
    progress: 100,
    tableauFileName: "Corp_Finance_Dashboard_2026.twb",
    createdDate: "2026-07-03",
    metadata: {
      name: "Enterprise Financial Performance",
      version: "19.1",
      author: "David Vance (Senior BI Architect)",
      createdDate: "2026-06-18",
      publishedDate: "2026-06-20",
      datasources: [
        {
          id: "federated.GeneralLedger",
          name: "GL_Transactions (ERP)",
          connection: {
            type: "oracle",
            server: "oracle-finance-vip.corp.internal",
            database: "FINPROD",
            schema: "FIN_GL_USER",
          },
          tables: [
            { table: "gl_transactions_fact", name: "GL_Transactions_Fact" },
            { table: "dim_accounts", name: "Dim_Accounts" },
            { table: "dim_cost_centers", name: "Dim_Cost_Centers" },
            { table: "dim_departments", name: "Dim_Departments" },
          ],
          columns: [
            { name: "Tx ID", id: "[Tx ID]", datatype: "integer", role: "dimension" },
            { name: "Posting Date", id: "[Posting Date]", datatype: "date", role: "dimension" },
            { name: "Account Code", id: "[Account Code]", datatype: "string", role: "dimension" },
            { name: "Cost Center ID", id: "[Cost Center ID]", datatype: "string", role: "dimension" },
            { name: "Debit Amount", id: "[Debit Amount]", datatype: "real", role: "measure" },
            { name: "Credit Amount", id: "[Credit Amount]", datatype: "real", role: "measure" },
            { name: "Account Name", id: "[Account Name]", datatype: "string", role: "dimension" },
            { name: "Department Code", id: "[Department Code]", datatype: "string", role: "dimension" },
          ],
          calculatedFields: [
            {
              name: "Net Posting Value",
              id: "[Net Posting Value]",
              formula: "ZN([Debit Amount]) - ZN([Credit Amount])",
              datatype: "real",
              role: "measure",
              convertedDax: "Net Posting Value = \nCOALESCE(SUM(GL_Transactions_Fact[Debit Amount]), 0) - COALESCE(SUM(GL_Transactions_Fact[Credit Amount]), 0)",
              convertedM: "Table.AddColumn(PreviousStep, \"Net Posting Value\", each (if [Debit Amount] = null then 0 else [Debit Amount]) - (if [Credit Amount] = null then 0 else [Credit Amount]))",
              explanation: "Tableau Zero-Null (ZN) expression is mapped to DAX COALESCE(..., 0) inside a SUM aggregation to guarantee zero output instead of blank values.",
              complexity: "Low",
              daxType: "Measure",
              warnings: ["Ensure column nullability constraints inside Power Query align with GL transaction logic."],
              status: "Verified",
            },
            {
              name: "Gross Margin (YTD)",
              id: "[Gross Margin (YTD)]",
              formula: "WINDOW_SUM(SUM([Net Posting Value]), FIRST(), 0)",
              datatype: "real",
              role: "measure",
              convertedDax: "Gross Margin (YTD) = \nTOTALYTD(\n    [Net Posting Value],\n    Dim_Calendar[Date]\n)",
              convertedM: "// Handled dynamically at reporting canvas tier.",
              explanation: "Tableau FIRST() relative window-sum mapped to direct DAX time intelligence TOTALYTD which handles financial fiscal year rollups out-of-the-box.",
              complexity: "High",
              daxType: "Measure",
              warnings: ["Requires marked date table. Validate financial year offset if fiscal start is not Jan 1."],
              status: "Verified",
            },
          ],
        },
      ],
      worksheets: [
        { name: "Ledger Sheet Balance", visualType: "Cross Tab / Text Table", filters: [] },
        { name: "Cost Center Burn Rate", visualType: "Bar Chart", filters: [{ column: "Cost Center ID" }] },
        { name: "EBITDA Performance YTD", visualType: "KPI Card", filters: [] },
      ],
      dashboards: [
        { name: "CFO Enterprise Dashboard", sheets: ["Ledger Sheet Balance", "Cost Center Burn Rate", "EBITDA Performance YTD"], layout: "Bento Layout" },
      ],
      parameters: [
        { id: "[Fiscal Year Start Month]", name: "Fiscal Year Start Month", datatype: "integer" },
      ],
      unsupportedFeatures: [
        "Tableau Custom Window Calculations (WINDOW_SUM) mapped to TOTALYTD",
      ],
    },
    dataModel: {
      schemaType: "Star Schema",
      factTables: ["GL_Transactions_Fact"],
      dimensionTables: ["Dim_Accounts", "Dim_Cost_Centers", "Dim_Departments", "Dim_Calendar"],
      bridgeTables: [],
      relationships: [
        { fromTable: "GL_Transactions_Fact", fromColumn: "AccountCode", toTable: "Dim_Accounts", toColumn: "AccountCode", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
        { fromTable: "GL_Transactions_Fact", fromColumn: "CostCenterID", toTable: "Dim_Cost_Centers", toColumn: "CostCenterID", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
        { fromTable: "GL_Transactions_Fact", fromColumn: "DeptCode", toTable: "Dim_Departments", toColumn: "DeptCode", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
        { fromTable: "GL_Transactions_Fact", fromColumn: "PostingDateKey", toTable: "Dim_Calendar", toColumn: "DateKey", cardinality: "Many-to-One (1:*)", direction: "Single (Dim filters Fact)", status: "Active" },
      ],
    },
    calculatedFields: [],
    validation: {
      rowCountMatch: true,
      columnCountMatch: true,
      totalsMatch: true,
      kpiMatch: true,
      discrepancyCount: 0,
      results: [
        { metricName: "GL Postings Row Count", tableauValue: 245100, powerBiValue: 245100, variance: 0, status: "Pass" },
        { metricName: "Trial Balance Reconciliation (Net)", tableauValue: 0, powerBiValue: 0, variance: 0, status: "Pass" },
        { metricName: "Year-To-Date Gross Margin", tableauValue: 18450000, powerBiValue: 18450000, variance: 0, status: "Pass" },
        { metricName: "Active Cost Centers Count", tableauValue: 48, powerBiValue: 48, variance: 0, status: "Pass" },
      ],
    },
    logs: [
      { timestamp: "11:20:00", level: "info", message: "Financial Performance project initialized." },
      { timestamp: "11:20:02", level: "success", message: "Parsed Oracle general ledger connections successfully." },
      { timestamp: "11:20:05", level: "success", message: "Calculated fields mapped. WINDOW_SUM relative calculations converted to dynamic DAX YTD measures." },
      { timestamp: "11:20:10", level: "success", message: "Reconciliation engine completed: Ledger balances matched with 100% precision." },
    ],
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "log-1",
    timestamp: "2026-07-07 10:14:02",
    project: "Global Superstore Retail",
    user: "mohamedyasin9168@gmail.com",
    action: "Workbook XML Analysis",
    status: "Success",
    details: "Successfully parsed Global_Superstore_v2026.twb. Identified 4 tables, 12 columns, and 5 calculation structures.",
  },
  {
    id: "log-2",
    timestamp: "2026-07-07 10:14:35",
    project: "Global Superstore Retail",
    user: "mohamedyasin9168@gmail.com",
    action: "AI Formula Conversion",
    status: "Success",
    details: "Converted 5 calculations to DAX/M. FIXED LOD expression transformed using CALCULATE/ALLEXCEPT.",
  },
  {
    id: "log-3",
    timestamp: "2026-07-07 10:14:48",
    project: "Global Superstore Retail",
    user: "mohamedyasin9168@gmail.com",
    action: "Data Model Validation",
    status: "Success",
    details: "Validated semantic model against Tableau source stats. All rows and aggregate metrics reconciled within 0.0% variance.",
  },
  {
    id: "log-4",
    timestamp: "2026-07-07 11:20:05",
    project: "Enterprise Financial Performance",
    user: "mohamedyasin9168@gmail.com",
    action: "AI Formula Conversion",
    status: "Warning",
    details: "WINDOW_SUM conversion completed with structural warnings. Manual marked-date-table registration required.",
  },
  {
    id: "log-5",
    timestamp: "2026-07-07 11:35:10",
    project: "Global Superstore Retail",
    user: "mohamedyasin9168@gmail.com",
    action: "Model Deployment (.BIM)",
    status: "Success",
    details: "Generated standard Tabular Model Schema .bim file for export into Tabular Editor / SSAS / Power BI XMLA.",
  },
];
